### ISSUE TITLE
Linkedin gets different scales as an image gallery

### ISSUE THREAD

**Issue by parruc** [collective/collective.ogtags#4]
Linkedin interprets the different og:image scales as multiple image of a gallery. The result is that you always share two identical images on linkedin.

Verified using "Share an update" from the profile page

**Comment by mauritsvanrees** [comment]
When I try 'Share an update' with http://www.zeelandia.nl/nieuws/nieuws-van-zeelandia/een-8-tal-tips-voor-extra-verkoop-bbq-brood (a Dutch site where we use collective.ogtags) I only see those images as options to choose from:

![screen shot 2016-06-22 at 16 09 56](https://cloud.githubusercontent.com/assets/210587/16269804/309f6e30-3894-11e6-8a03-6e9636e153d4.png)

Note: I did not actually add an update, I only looked at the preview.
Are you seeing something different?

If so, I don't think there is anything we can do about this: facebook wants different sizes, so we must supply multiple tags. As workaround, you could go to the `@@imaging-controlpanel` and remove `og_fbl` and `og_fb` from the scales.

**Comment by parruc** [comment]
My error. Seeing the arrows in the sharing preview I thought they would have been visible on the published version too but they don't.

It's not a gallery like I thought but a smart way to let you choose which image you want to use. 

Sorry for bothering with this non-issue ;-)

**Comment by mauritsvanrees** [comment]
No problem. :-)
